# Generated by Django 3.2.5 on 2021-07-20 12:38

from django.db import migrations, models
import elections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=50)),
                ('cover_img', models.ImageField(blank=True, upload_to=elections.models.user_dir_path)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=50)),
            ],
        ),
    ]
