# Generated by Django 3.2.5 on 2021-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='url',
            field=models.SlugField(unique=True),
        ),
    ]
