# Generated by Django 3.2.5 on 2021-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_election_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='url',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
