# Generated by Django 3.2.5 on 2021-07-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_candidate_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='url',
            new_name='url_extid',
        ),
    ]
